#pragma once

enum OPERATION_MODE
{
	MODE_UNINITIALIZED = -1,
	KEY_GENERATION_MODE = 0,
	DECRYPTION_KEY_GENERATION_MODE,
	DECRYPT_MODE,
	ENCRYPT_MODE,
	GENERATE_AND_ENCRYPT_MODE,
	GENERATE_AND_DECRYPT_MODE,
} typedef OPERATION_MODE;

