#ifndef OUTPUTFORMAT_H
#define OUTPUTFORMAT_H

enum FILE_FORMAT
{
    OUTPUT_FORMAT_UNINITIALIZED = -1,
    OUTPUT_FORMAT_BINARY = 0,
    OUTPUT_FORMAT_TEXT,

    NUMBER_OF_OUTPUT_FORMATS
} typedef FILE_FORMAT;

#endif //OUTPUTFORMAT_H
