#pragma once

#define STATUS_SUCCESS(status) (status == STATUS_CODE_SUCCESS)
#define STATUS_FAILED(status) (status != STATUS_CODE_SUCCESS)

enum STATUS_CODE
{
	STATUS_CODE_UNINITIALIZED = -1,
	STATUS_CODE_SUCCESS = 0,
	STATUS_CODE_INVALID_ARGUMENT,
	STATUS_CODE_ERROR_MEMORY_ALLOCATION

} typedef STATUS_CODE;

