name: Windows Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4  
        with:
          submodules: recursive
      - run: cmake -S GaloisFieldHillCipher -B GaloisFieldHillCipher/build
      - run: cmake --build GaloisFieldHillCipher/build -- -j$(nproc)
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: GaloisFieldHillCipher/build/UnitTests
