name: Linux Memory Leak Test

on:
  workflow_run:
    workflows: ["Linux Build"]
    types:
      - completed

jobs:
  valgrind-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - run: cd GaloisFieldHillCipher
      - run: sudo apt-get update && sudo apt-get install -y valgrind
      - uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: ./build
      - run: chmod +x ./build/GaloisFieldHillCipher
      - run: echo "Example plaintext" > plaintext.txt
      - name: Valgrind - Generate encryption key (ek)
        run: |
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --track-origins=yes \
                   --verbose \
                   --log-file=valgrind-ek.txt \
                   ./build/GaloisFieldHillCipher -m ek -o encryption_key.bin -d 3
      - name: Valgrind - Generate decryption key (dk)
        run: |
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --track-origins=yes \
                   --verbose \
                   --log-file=valgrind-dk.txt \
                   ./build/GaloisFieldHillCipher -m dk -k encryption_key.bin -o decryption_key.bin -d 3
      - name: Valgrind - Encrypt (e)
        run: |
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --track-origins=yes \
                   --verbose \
                   --log-file=valgrind-e.txt \
                   ./build/GaloisFieldHillCipher -m e -i plaintext.txt -o encrypted.bin -k encryption_key.bin -d 3
      - name: Valgrind - Decrypt (d)
        run: |
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --track-origins=yes \
                   --verbose \
                   --log-file=valgrind-d.txt \
                   ./build/GaloisFieldHillCipher -m d -i encrypted.bin -o decrypted.txt -k decryption_key.bin -d 3
      - name: Valgrind - Generate and encrypt (ge)
        run: |
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --track-origins=yes \
                   --verbose \
                   --log-file=valgrind-ge.txt \
                   ./build/GaloisFieldHillCipher -m ge -i plaintext.txt -o ge_encrypted.bin -k ge_key.bin -d 3
      - name: Valgrind - Generate and decrypt (gd)
        run: |
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --track-origins=yes \
                   --verbose \
                   --log-file=valgrind-gd.txt \
                   ./build/GaloisFieldHillCipher -m gd -i encrypted.bin -o gd_decrypted.txt -k encryption_key.bin -d 3
