name: Windows Test

on:
  workflow_run:
    workflows: ["Windows Build"]
    types:
      - completed

jobs:
  test-windows:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: .\GaloisFieldHillCipher\build
      - run: .\GaloisFieldHillCipher\build\UnitTests.exe
