name: Linux Test

on:
  workflow_run:
    workflows: ["Linux Build"]
    types:
      - completed

jobs:
  test-linux:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: linux-build
          path: ./GaloisFieldHillCipher/build
      - run: ./GaloisFieldHillCipher/build/UnitTests
